[theme]
primaryColor="#1e88e5"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#31333F"

[server]
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
